from cx_Freeze import setup, Executable

# Import version generated by CI
try:
    from kboom_version import __version__ as version
except ImportError:
    version = "0.0.0-dev"

build_options = {
    'packages': [],
    'excludes': []
}

base = 'gui'  # use None if you don't want GUI mode on Linux

executables = [
    Executable(
        'main.py',
        base=base,
        target_name=f'k-boom-studio-{version}'
    )
]

setup(
    name='K-Boom-Studio',
    version=version,
    description='K-Boom-Studio is a firework sequencing utility used to create sequence files for K-Boom-Player',
    options={'build_exe': build_options},
    executables=executables
)